"""
Name: Chukwunonso Kuzue
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
Create a program that will play the cow and bulls game with the user . the game works like this
randomly generate a 4 digit number. Ask the user to generate a 4 digit number. For
every digit that the user guess in the correct place, they have a cow. For every
digit the user guessed in the wrong place, they have a bull.

Every time the user makes a guess, tell them how many cows and bulls they have.
Once the user guesses the correct number the game is over. Keep
track of the number of guesses the user makes throughout the game and tell the user at the end.

say the number generated by the user is 1038. An example iteration could look like this
welcome to cow and bull’s game

Enter a number:

>>> 1234
2 cows, 0 bulls
>>> 1286
1 cow , 1 bulls
. . .
until the user guesses the number

pseudo code
1. import random, generate a 4-digit number ensuring its a string so it can be iterated
2. using the input function ask the user for a 4-digit number. input
3. iterate through the users guesses and evaluate if it contains the same digit as the computer generated digits and in the right position. if yes print to the user a 'cow' else 'bull'
4. for each iterate of guess implement guess count,telling them how many cow or bull they have
5. The game ends once the user makes the correct guesses 
6. keep track of the number of guesses the user makes throughout the game AND tell this to the user
""" 
import random

def cow_And_Bull_Game(user_Input):

    
    random_Number = str(random.randrange(1000, 10_000)) # converted this to a string for possible iteration
    print(random_Number)

    #variables to track the cow and bull ccount
    cow_Count = 0
    bull_Count = 0

    for i in range(4):
        if random_Number[i] == user_Input[i]:
            cow_Count += 1
        elif random_Number[i] in user_Input:
            bull_Count += 1

    if cow_Count <= 1:
        cow_plural = 'cow'
    else:
        cow_plural ='cows'
    
    if bull_Count <= 1 :
        bull_plural = 'bull'

    else:
        bull_plural ='bulls'
    

    
    print(f"\n{cow_Count} {cow_plural}  {bull_Count} {bull_plural}\n")
    if cow_Count == 4:
        print("Congratulations on winnning the game!!! ")


while True:
    print("Welcome to cow and Bull's Game >>>\n")

    user_Input = input("Enter a 4 digit number \n>>>")

    if len(user_Input) != 4 or not user_Input.isdigit(): #accounting for edge cases of index error
        print("\ninvalid input! Enter a 4 digit number >>> \n")
        continue

    cow_And_Bull_Game(user_Input) #run the game